### ISSUE TITLE
infografía _Sandy Marissa Gs

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-SandyMarissaGs#1]
[Conceptos y funciones de una librerias o componentes y su aplicacion en las Apps.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-SandyMarissaGs/files/14577496/Conceptos.y.funciones.de.una.librerias.o.componentes.y.su.aplicacion.en.las.Apps.pdf)

**Comment by ErikCuevas03** [comment]
De acuerdo la rubrica la calificación  correspondiente es de 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
